# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tracking.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrackingWindow(object):
    def setupUi(self, TrackingWindow):
        TrackingWindow.setObjectName("TrackingWindow")
        TrackingWindow.resize(1240, 770)
        self.centralwidget = QtWidgets.QWidget(TrackingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.open_img_label = QtWidgets.QLabel(self.frame_2)
        self.open_img_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.open_img_label.setStyleSheet("font: 9pt \"黑体\";")
        self.open_img_label.setObjectName("open_img_label")
        self.gridLayout_2.addWidget(self.open_img_label, 1, 0, 1, 1)
        self.target_window = QtWidgets.QLabel(self.frame_2)
        self.target_window.setMaximumSize(QtCore.QSize(300, 220))
        self.target_window.setText("")
        self.target_window.setObjectName("target_window")
        self.gridLayout_2.addWidget(self.target_window, 0, 0, 1, 2)
        self.img_path_button = QtWidgets.QPushButton(self.frame_2)
        self.img_path_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.img_path_button.setObjectName("img_path_button")
        self.gridLayout_2.addWidget(self.img_path_button, 1, 1, 1, 1)
        self.open_video_label = QtWidgets.QLabel(self.frame_2)
        self.open_video_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.open_video_label.setStyleSheet("font: 9pt \"黑体\";")
        self.open_video_label.setObjectName("open_video_label")
        self.gridLayout_2.addWidget(self.open_video_label, 3, 0, 1, 1)
        self.video_path_button = QtWidgets.QPushButton(self.frame_2)
        self.video_path_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.video_path_button.setObjectName("video_path_button")
        self.gridLayout_2.addWidget(self.video_path_button, 3, 1, 1, 1)
        self.start_button = QtWidgets.QPushButton(self.frame_2)
        self.start_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.start_button.setStyleSheet("font: 9pt \"黑体\";")
        self.start_button.setObjectName("start_button")
        self.gridLayout_2.addWidget(self.start_button, 5, 0, 1, 1)
        self.exit_button = QtWidgets.QPushButton(self.frame_2)
        self.exit_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.exit_button.setStyleSheet("font: 9pt \"黑体\";")
        self.exit_button.setObjectName("exit_button")
        self.gridLayout_2.addWidget(self.exit_button, 5, 1, 1, 1)
        self.target_img_path = QtWidgets.QLineEdit(self.frame_2)
        self.target_img_path.setMaximumSize(QtCore.QSize(16777215, 30))
        self.target_img_path.setObjectName("target_img_path")
        self.gridLayout_2.addWidget(self.target_img_path, 2, 0, 1, 2)
        self.test_video_path = QtWidgets.QLineEdit(self.frame_2)
        self.test_video_path.setMaximumSize(QtCore.QSize(16777215, 30))
        self.test_video_path.setObjectName("test_video_path")
        self.gridLayout_2.addWidget(self.test_video_path, 4, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.video_window = QtWidgets.QLabel(self.frame)
        self.video_window.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.video_window.setText("")
        self.video_window.setObjectName("video_window")
        self.gridLayout_3.addWidget(self.video_window, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        TrackingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrackingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1240, 26))
        self.menubar.setObjectName("menubar")
        TrackingWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TrackingWindow)
        self.statusbar.setObjectName("statusbar")
        TrackingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TrackingWindow)
        QtCore.QMetaObject.connectSlotsByName(TrackingWindow)

    def retranslateUi(self, TrackingWindow):
        _translate = QtCore.QCoreApplication.translate
        TrackingWindow.setWindowTitle(_translate("TrackingWindow", "基于SIFT和KCF的运动目标匹配与跟踪：特定目标追踪"))
        self.open_img_label.setText(_translate("TrackingWindow", "打开目标图像："))
        self.img_path_button.setText(_translate("TrackingWindow", "..."))
        self.open_video_label.setText(_translate("TrackingWindow", "打开测试视频："))
        self.video_path_button.setText(_translate("TrackingWindow", "..."))
        self.start_button.setText(_translate("TrackingWindow", "开始检测并跟踪"))
        self.exit_button.setText(_translate("TrackingWindow", "退出"))

